dist: trusty

sudo: false

language: python

cache: pip

addons:
  postgresql: 10
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
      - postgresql-10
      - postgis

python:
  - "3.6"

env:
  - DJANGO_SETTINGS_MODULE="base.settings.dev"
  - DJANGO_ALLOWED_HOSTS="*"
  - DJANGO_DEBUG="true"
  - DJANGO_SECRET_KEY="smb_ci"
  - DJANGO_DATABASE_URL="postgis://smb_ci:smb_ci@10.0.1.66:5432/smb_ci"
  - DJANGO_PUBLIC_URL="http://127.0.0.1:8000"
  - DJANGO_EMAIL_HOST_USER=
  - DJANGO_EMAIL_HOST_PASSWORD=
  - KEYCLOAK_BASE_URL="http://127.0.1:8080"
  - KEYCLOAK_REALM="demo"
  - DJANGO_KEYCLOAK_CLIENT_ID=demoapp
  - KEYCLOAK_ADMIN_USERNAME="realmboss1"
  - KEYCLOAK_ADMIN_PASSWORD="123456"

before_script:
  - bash bin/travis-install-keycloak.sh
  - psql --user=postgres --command="CREATE USER smb_ci WITH SUPERUSER PASSWORD 'smb_ci'"
  - psql --user=postgres --command="CREATE DATABASE smb_ci WITH OWNER smb_ci"
  - psql --user=postgres --dbname=smb_ci --command="CREATE EXTENSION postgis"

install:
  - pip install --requirement requirements/dev.txt

script:
  - pytest

